alias ee='emacs ~/clojure/experienced'
alias uu='sudo apt-get update;sudo apt-get upgrade'
alias srch='apt-cache search'
alias q='exit'
alias ainstall='sudo apt-get install'
alias kpak='dpkg -l|grep'
alias md='mkdir'
alias l='less'
alias ll='ls -l'
alias pi='ssh -l pi raspberrypi'
alias lighttable='/home/henrik/bin/LightTable/LightTable'
alias lrs='lein ring server'
alias gitlog='git log --pretty=format:"%h - %an %ai: %s" -n 20﻿'
alias gdiff='git diff --name-only'
alias qq='shutdown -h -t 0'
alias rr='shutdown -r -t 0'
alias chrome='chromium-browser'
alias config='/usr/bin/git --git-dir=$HOME/.myconf/ --work-tree=$HOME'